Repository paketo-buildpacks/syft, pull requests merged in 2021-12, with the labels that each got.

#7 Add update workflow
  .github/pipeline-descriptor.yml
  .github/workflows/update-syft-cli.yml
Labels: semver:patch, type:task

#11 Bump libpak from 1.56.2 to 1.57.0
  go.mod
  go.sum
Labels: semver:patch, type:dependency-upgrade

#17 Improve syft scanning times and skip internet calls to check for updates
  syft/syft.go
  syft/syft_test.go
Labels: semver:patch, type:bug
